
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSASSIGN COMMA DIVIDE ID INT LBRACE LPAREN MINUS NUMBER PLUS PRINT RBRACE RETURN RPAREN SEMI TIMESprogram : functionsfunctions : functions function\n                 | functionfunction : INT ID LPAREN params RPAREN blockparams : param_list\n              | emptyparam_list : param_list COMMA param\n                  | paramparam : INT IDblock : LBRACE declarations statements RBRACEdeclarations : declarations declaration\n                    | emptydeclaration : INT ID ASSIGN expression SEMI\n                   | INT ID SEMIstatements : statements statement\n                  | emptystatement : ID ASSIGN expression SEMIstatement : PRINT LPAREN ID RPAREN SEMIstatement : RETURN expression SEMIexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : IDexpression : MINUS expression %prec UMINUSempty :'
    
_lr_action_items = {'INT':([0,2,3,5,7,15,16,17,19,20,22,25,39,57,],[4,4,-3,-2,8,8,-4,-28,24,-12,-11,-10,-14,-13,]),'$end':([1,2,3,5,16,25,],[0,-1,-3,-2,-4,-10,]),'ID':([4,8,17,19,20,21,22,23,24,26,29,31,32,34,35,38,39,42,43,44,45,46,50,57,58,],[6,13,-28,-28,-12,27,-11,-16,30,-15,37,37,41,37,37,37,-14,-19,37,37,37,37,-17,-13,-18,]),'LPAREN':([6,28,29,31,34,35,38,43,44,45,46,],[7,32,35,35,35,35,35,35,35,35,35,]),'RPAREN':([7,9,10,11,12,13,18,36,37,41,47,48,52,53,54,55,56,],[-28,14,-5,-6,-8,-9,-7,-25,-26,51,-27,56,-20,-21,-22,-23,-24,]),'COMMA':([10,12,13,18,],[15,-8,-9,-7,]),'LBRACE':([14,],[17,]),'RBRACE':([17,19,20,21,22,23,26,39,42,50,57,58,],[-28,-28,-12,25,-11,-16,-15,-14,-19,-17,-13,-18,]),'PRINT':([17,19,20,21,22,23,26,39,42,50,57,58,],[-28,-28,-12,28,-11,-16,-15,-14,-19,-17,-13,-18,]),'RETURN':([17,19,20,21,22,23,26,39,42,50,57,58,],[-28,-28,-12,29,-11,-16,-15,-14,-19,-17,-13,-18,]),'ASSIGN':([27,30,],[31,38,]),'NUMBER':([29,31,34,35,38,43,44,45,46,],[36,36,36,36,36,36,36,36,36,]),'MINUS':([29,31,33,34,35,36,37,38,40,43,44,45,46,47,48,49,52,53,54,55,56,],[34,34,44,34,34,-25,-26,34,44,34,34,34,34,-27,44,44,-20,-21,-22,-23,-24,]),'SEMI':([30,33,36,37,40,47,49,51,52,53,54,55,56,],[39,42,-25,-26,50,-27,57,58,-20,-21,-22,-23,-24,]),'PLUS':([33,36,37,40,47,48,49,52,53,54,55,56,],[43,-25,-26,43,-27,43,43,-20,-21,-22,-23,-24,]),'TIMES':([33,36,37,40,47,48,49,52,53,54,55,56,],[45,-25,-26,45,-27,45,45,45,45,-22,-23,-24,]),'DIVIDE':([33,36,37,40,47,48,49,52,53,54,55,56,],[46,-25,-26,46,-27,46,46,46,46,-22,-23,-24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'functions':([0,],[2,]),'function':([0,2,],[3,5,]),'params':([7,],[9,]),'param_list':([7,],[10,]),'empty':([7,17,19,],[11,20,23,]),'param':([7,15,],[12,18,]),'block':([14,],[16,]),'declarations':([17,],[19,]),'statements':([19,],[21,]),'declaration':([19,],[22,]),'statement':([21,],[26,]),'expression':([29,31,34,35,38,43,44,45,46,],[33,40,47,48,49,52,53,54,55,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> functions','program',1,'p_program','tac.py',77),
  ('functions -> functions function','functions',2,'p_functions','tac.py',81),
  ('functions -> function','functions',1,'p_functions','tac.py',82),
  ('function -> INT ID LPAREN params RPAREN block','function',6,'p_function','tac.py',86),
  ('params -> param_list','params',1,'p_params','tac.py',92),
  ('params -> empty','params',1,'p_params','tac.py',93),
  ('param_list -> param_list COMMA param','param_list',3,'p_param_list','tac.py',97),
  ('param_list -> param','param_list',1,'p_param_list','tac.py',98),
  ('param -> INT ID','param',2,'p_param','tac.py',102),
  ('block -> LBRACE declarations statements RBRACE','block',4,'p_block','tac.py',106),
  ('declarations -> declarations declaration','declarations',2,'p_declarations','tac.py',110),
  ('declarations -> empty','declarations',1,'p_declarations','tac.py',111),
  ('declaration -> INT ID ASSIGN expression SEMI','declaration',5,'p_declaration','tac.py',117),
  ('declaration -> INT ID SEMI','declaration',3,'p_declaration','tac.py',118),
  ('statements -> statements statement','statements',2,'p_statements','tac.py',127),
  ('statements -> empty','statements',1,'p_statements','tac.py',128),
  ('statement -> ID ASSIGN expression SEMI','statement',4,'p_statement_expr','tac.py',134),
  ('statement -> PRINT LPAREN ID RPAREN SEMI','statement',5,'p_statement_print','tac.py',140),
  ('statement -> RETURN expression SEMI','statement',3,'p_statement_return','tac.py',144),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','tac.py',149),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','tac.py',150),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','tac.py',151),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','tac.py',152),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','tac.py',169),
  ('expression -> NUMBER','expression',1,'p_expression_number','tac.py',173),
  ('expression -> ID','expression',1,'p_expression_id','tac.py',179),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','tac.py',183),
  ('empty -> <empty>','empty',0,'p_empty','tac.py',195),
]
